### PR TITLE
Fixes: Method setUploadButton() works differently as documented 

### LINKED ISSUE #122: Method setUploadButton() works differently as documented
**Vaadin Upload Flow Version 1.3.0**
The javadoc of the method `setUploadButton()` says "_Set the component as the actionable button inside the upload component, that starts the upload of the selected files._", but in fact the button sent as a parameter will open the dialog for choosing the files to be upload, and not start the actual upload of them (for example if `setAutoUpload(false)` is called previously).

### PR DESCRIPTION
**Pull request by hongduc-phan**
Fixes #122

### CODE REVIEW

File: vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java [hunk 1]
```diff
@@ -264,10 +264,10 @@ public void setAcceptedFileTypes(String... acceptedFileTypes) {
 
     /**
      * Set the component as the actionable button inside the upload component,
-     * that starts the upload of the selected files.
+     * that opens the dialog for choosing the files to be upload.
      *
      * @param uploadButton
-     *            the component to be clicked by the user to start the upload,
+     *            the component to be clicked by the user to open the dialog,
      *            or <code>null</code> to clear it
```
[the remark this answers is not in the document]
Comment (hongduc-phan) [reply vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java]: done! It will use the vaadin-button as the actionable button if in case using null

File: vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java [hunk 2]
```diff
@@ -264,11 +264,11 @@ public void setAcceptedFileTypes(String... acceptedFileTypes) {
...
     /**
      * Set the component as the actionable button inside the upload component,
-     * that starts the upload of the selected files.
+     * that opens the dialog for choosing the files to be upload.
      *
      * @param uploadButton
-     *            the component to be clicked by the user to start the upload,
-     *            or <code>null</code> to clear it
+     *            the component to be clicked by the user to open the dialog,
+     *            or <code>null</code> to use vaadin-button as the actionable button
```
Comment (DiegoCardoso) [inline vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java]: Just to be more clear, it could be
```suggestion
     *            or <code>null</code> to reset to the default button
```

Comment (hongduc-phan) [reply vaadin-upload-flow/src/main/java/com/vaadin/flow/component/upload/Upload.java]: done
